// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package systemdb

import (
	"database/sql"
)

type ActivationToken struct {
	Verifier  []byte `json:"verifier"`
	UserID    string `json:"user_id"`
	Purpose   string `json:"purpose"`
	ExpiresAt int64  `json:"expires_at"`
	CreatedAt int64  `json:"created_at"`
}

type AdmissionClock struct {
	Singleton       int64  `json:"singleton"`
	LastEffectiveAt int64  `json:"last_effective_at"`
	ProcessEpoch    string `json:"process_epoch"`
}

type AnthropicFile struct {
	ID          string `json:"id"`
	OwnerUserID string `json:"owner_user_id"`
	KeyID       string `json:"key_id"`
	Filename    string `json:"filename"`
	MimeType    string `json:"mime_type"`
	SizeBytes   int64  `json:"size_bytes"`
	Ciphertext  []byte `json:"ciphertext"`
	Nonce       []byte `json:"nonce"`
	CreatedAt   int64  `json:"created_at"`
	ExpiresAt   int64  `json:"expires_at"`
}

type ApiKey struct {
	ID                string        `json:"id"`
	OwnerUserID       string        `json:"owner_user_id"`
	Label             string        `json:"label"`
	State             string        `json:"state"`
	ScopesJson        string        `json:"scopes_json"`
	ModelPatternsJson string        `json:"model_patterns_json"`
	ConnectionIdsJson string        `json:"connection_ids_json"`
	ExpiresAt         sql.NullInt64 `json:"expires_at"`
	Revision          int64         `json:"revision"`
	CreatedAt         int64         `json:"created_at"`
	UpdatedAt         int64         `json:"updated_at"`
}

type ApiKeySecret struct {
	Selector  string        `json:"selector"`
	Verifier  []byte        `json:"verifier"`
	KeyID     string        `json:"key_id"`
	CreatedAt int64         `json:"created_at"`
	ExpiresAt sql.NullInt64 `json:"expires_at"`
	RevokedAt sql.NullInt64 `json:"revoked_at"`
}

type Attempt struct {
	ID                         string         `json:"id"`
	RequestID                  string         `json:"request_id"`
	Ordinal                    int64          `json:"ordinal"`
	ConnectionID               string         `json:"connection_id"`
	ModelID                    string         `json:"model_id"`
	PriceVersionID             sql.NullString `json:"price_version_id"`
	State                      string         `json:"state"`
	UsageStatus                string         `json:"usage_status"`
	EstimatedTokens            int64          `json:"estimated_tokens"`
	InputTokens                sql.NullInt64  `json:"input_tokens"`
	OutputTokens               sql.NullInt64  `json:"output_tokens"`
	EstimatedCostNanos         sql.NullInt64  `json:"estimated_cost_nanos"`
	AsRecordedCostNanos        sql.NullInt64  `json:"as_recorded_cost_nanos"`
	RestatedCostNanos          sql.NullInt64  `json:"restated_cost_nanos"`
	StartedAt                  int64          `json:"started_at"`
	FinishedAt                 sql.NullInt64  `json:"finished_at"`
	UpstreamModelRecordID      string         `json:"upstream_model_record_id"`
	UpstreamModelID            string         `json:"upstream_model_id"`
	ConnectionRevision         int64          `json:"connection_revision"`
	TargetDialect              string         `json:"target_dialect"`
	TargetOperation            string         `json:"target_operation"`
	TranslationApplied         int64          `json:"translation_applied"`
	RequestToolCount           int64          `json:"request_tool_count"`
	ResponseToolCallCount      int64          `json:"response_tool_call_count"`
	ToolCallStatus             string         `json:"tool_call_status"`
	SelectionReason            string         `json:"selection_reason"`
	RejectedCandidatesJson     string         `json:"rejected_candidates_json"`
	CacheCreationInputTokens   sql.NullInt64  `json:"cache_creation_input_tokens"`
	CacheReadInputTokens       sql.NullInt64  `json:"cache_read_input_tokens"`
	CacheCreation5mInputTokens sql.NullInt64  `json:"cache_creation_5m_input_tokens"`
	CacheCreation1hInputTokens sql.NullInt64  `json:"cache_creation_1h_input_tokens"`
	WebSearchMaxCalls          sql.NullInt64  `json:"web_search_max_calls"`
	WebSearchCallCount         sql.NullInt64  `json:"web_search_call_count"`
	PriceQuotedAt              sql.NullInt64  `json:"price_quoted_at"`
	WebFetchPresent            int64          `json:"web_fetch_present"`
}

type AuditEvent struct {
	ID           string         `json:"id"`
	ActorUserID  sql.NullString `json:"actor_user_id"`
	Action       string         `json:"action"`
	ResourceType string         `json:"resource_type"`
	ResourceID   string         `json:"resource_id"`
	DetailJson   string         `json:"detail_json"`
	CreatedAt    int64          `json:"created_at"`
}

type BackupJob struct {
	ID                 string        `json:"id"`
	State              string        `json:"state"`
	Destination        string        `json:"destination"`
	ArchiveName        string        `json:"archive_name"`
	Checksum           string        `json:"checksum"`
	SizeBytes          int64         `json:"size_bytes"`
	SnapshotGeneration string        `json:"snapshot_generation"`
	Error              string        `json:"error"`
	StartedAt          int64         `json:"started_at"`
	FinishedAt         sql.NullInt64 `json:"finished_at"`
}

type BucketState struct {
	PolicyID        string `json:"policy_id"`
	RemainingUnits  int64  `json:"remaining_units"`
	RefillRemainder int64  `json:"refill_remainder"`
	LastRefillAt    int64  `json:"last_refill_at"`
	LastEffectiveAt int64  `json:"last_effective_at"`
}

type CatalogCandidate struct {
	Provider              string        `json:"provider"`
	ModelID               string        `json:"model_id"`
	Label                 string        `json:"label"`
	CapabilitiesJson      string        `json:"capabilities_json"`
	InputNanosPerMillion  sql.NullInt64 `json:"input_nanos_per_million"`
	OutputNanosPerMillion sql.NullInt64 `json:"output_nanos_per_million"`
	Free                  int64         `json:"free"`
	Source                string        `json:"source"`
	SourceVersion         string        `json:"source_version"`
	DiscoveredAt          int64         `json:"discovered_at"`
}

type CatalogRefreshState struct {
	Singleton            int64         `json:"singleton"`
	SourceUrl            string        `json:"source_url"`
	SourceVersion        string        `json:"source_version"`
	LastCheckedAt        sql.NullInt64 `json:"last_checked_at"`
	LastError            string        `json:"last_error"`
	RefreshEnabled       int64         `json:"refresh_enabled"`
	RefreshIntervalHours int64         `json:"refresh_interval_hours"`
}

type ConcurrencyLease struct {
	PolicyID     string         `json:"policy_id"`
	LeaseKind    string         `json:"lease_kind"`
	LeaseID      string         `json:"lease_id"`
	RequestID    string         `json:"request_id"`
	AttemptID    sql.NullString `json:"attempt_id"`
	ProcessEpoch string         `json:"process_epoch"`
	CreatedAt    int64          `json:"created_at"`
}

type Conversation struct {
	ID           string        `json:"id"`
	OwnerUserID  string        `json:"owner_user_id"`
	KeyID        string        `json:"key_id"`
	MetadataJson string        `json:"metadata_json"`
	CreatedAt    int64         `json:"created_at"`
	DeletedAt    sql.NullInt64 `json:"deleted_at"`
	Revision     int64         `json:"revision"`
}

type ConversationItem struct {
	ConversationID string `json:"conversation_id"`
	ID             string `json:"id"`
	Ordinal        int64  `json:"ordinal"`
	BodyJson       []byte `json:"body_json"`
	CreatedAt      int64  `json:"created_at"`
}

type CostAssessment struct {
	ID                 string `json:"id"`
	AttemptID          string `json:"attempt_id"`
	PriceVersionID     string `json:"price_version_id"`
	CalculationVersion int64  `json:"calculation_version"`
	Kind               string `json:"kind"`
	AmountNanos        int64  `json:"amount_nanos"`
	DeltaNanos         int64  `json:"delta_nanos"`
	CreatedAt          int64  `json:"created_at"`
}

type EventOutbox struct {
	Sequence    int64          `json:"sequence"`
	ID          string         `json:"id"`
	EventType   string         `json:"event_type"`
	RequestID   sql.NullString `json:"request_id"`
	AttemptID   sql.NullString `json:"attempt_id"`
	PayloadJson string         `json:"payload_json"`
	CreatedAt   int64          `json:"created_at"`
	DeliveredAt sql.NullInt64  `json:"delivered_at"`
}

type GatewayMetadatum struct {
	Key       string `json:"key"`
	Value     string `json:"value"`
	UpdatedAt string `json:"updated_at"`
}

type GeminiFile struct {
	ID          string `json:"id"`
	OwnerUserID string `json:"owner_user_id"`
	KeyID       string `json:"key_id"`
	DisplayName string `json:"display_name"`
	MimeType    string `json:"mime_type"`
	Bytes       int64  `json:"bytes"`
	Ciphertext  []byte `json:"ciphertext"`
	Nonce       []byte `json:"nonce"`
	CreatedAt   int64  `json:"created_at"`
	ExpiresAt   int64  `json:"expires_at"`
}

type GeminiUpload struct {
	ID            string         `json:"id"`
	OwnerUserID   string         `json:"owner_user_id"`
	KeyID         string         `json:"key_id"`
	DisplayName   string         `json:"display_name"`
	MimeType      string         `json:"mime_type"`
	ExpectedBytes int64          `json:"expected_bytes"`
	ReceivedBytes int64          `json:"received_bytes"`
	RequestedID   sql.NullString `json:"requested_id"`
	Status        string         `json:"status"`
	FileID        sql.NullString `json:"file_id"`
	CompletedAt   sql.NullInt64  `json:"completed_at"`
	Ciphertext    []byte         `json:"ciphertext"`
	Nonce         []byte         `json:"nonce"`
	CreatedAt     int64          `json:"created_at"`
	ExpiresAt     int64          `json:"expires_at"`
}

type LimitPolicy struct {
	ID               string `json:"id"`
	ScopeKind        string `json:"scope_kind"`
	ScopeID          string `json:"scope_id"`
	Metric           string `json:"metric"`
	Algorithm        string `json:"algorithm"`
	Period           string `json:"period"`
	WindowSeconds    int64  `json:"window_seconds"`
	LimitUnits       int64  `json:"limit_units"`
	RefillUnits      int64  `json:"refill_units"`
	RefillIntervalMs int64  `json:"refill_interval_ms"`
	Enabled          int64  `json:"enabled"`
	Revision         int64  `json:"revision"`
	CreatedAt        int64  `json:"created_at"`
	UpdatedAt        int64  `json:"updated_at"`
}

type LoginThrottle struct {
	Subject         []byte `json:"subject"`
	WindowStartedAt int64  `json:"window_started_at"`
	Failures        int64  `json:"failures"`
	BlockedUntil    int64  `json:"blocked_until"`
}

type MediaJob struct {
	ID               string        `json:"id"`
	OwnerUserID      string        `json:"owner_user_id"`
	KeyID            string        `json:"key_id"`
	RequestID        string        `json:"request_id"`
	AttemptID        string        `json:"attempt_id"`
	ModelID          string        `json:"model_id"`
	ConnectionID     string        `json:"connection_id"`
	Provider         string        `json:"provider"`
	ProviderJobID    string        `json:"provider_job_id"`
	MediaType        string        `json:"media_type"`
	State            string        `json:"state"`
	InputCiphertext  []byte        `json:"input_ciphertext"`
	InputNonce       []byte        `json:"input_nonce"`
	InputBytes       int64         `json:"input_bytes"`
	OutputCiphertext []byte        `json:"output_ciphertext"`
	OutputNonce      []byte        `json:"output_nonce"`
	OutputBytes      int64         `json:"output_bytes"`
	ErrorJson        string        `json:"error_json"`
	CancelRequested  int64         `json:"cancel_requested"`
	PollFailures     int64         `json:"poll_failures"`
	NextPollAt       int64         `json:"next_poll_at"`
	Revision         int64         `json:"revision"`
	CreatedAt        int64         `json:"created_at"`
	UpdatedAt        int64         `json:"updated_at"`
	CompletedAt      sql.NullInt64 `json:"completed_at"`
}

type MessageBatch struct {
	ID                string        `json:"id"`
	OwnerUserID       string        `json:"owner_user_id"`
	KeyID             string        `json:"key_id"`
	ProcessingStatus  string        `json:"processing_status"`
	CancelRequested   int64         `json:"cancel_requested"`
	CreatedAt         int64         `json:"created_at"`
	CancelInitiatedAt sql.NullInt64 `json:"cancel_initiated_at"`
	EndedAt           sql.NullInt64 `json:"ended_at"`
	ExpiresAt         int64         `json:"expires_at"`
}

type MessageBatchItem struct {
	BatchID             string         `json:"batch_id"`
	Ordinal             int64          `json:"ordinal"`
	CustomID            string         `json:"custom_id"`
	ParamsJson          []byte         `json:"params_json"`
	ResultJson          []byte         `json:"result_json"`
	State               string         `json:"state"`
	RequestID           sql.NullString `json:"request_id"`
	AttemptID           sql.NullString `json:"attempt_id"`
	ReservedResultBytes int64          `json:"reserved_result_bytes"`
	LeaseEpoch          string         `json:"lease_epoch"`
	ClaimedAt           sql.NullInt64  `json:"claimed_at"`
	DispatchStartedAt   sql.NullInt64  `json:"dispatch_started_at"`
	FinishedAt          sql.NullInt64  `json:"finished_at"`
}

type OpenaiBatch struct {
	ID                   string         `json:"id"`
	OwnerUserID          string         `json:"owner_user_id"`
	KeyID                string         `json:"key_id"`
	InputFileID          string         `json:"input_file_id"`
	Endpoint             string         `json:"endpoint"`
	CompletionWindow     string         `json:"completion_window"`
	ModelID              string         `json:"model_id"`
	Status               string         `json:"status"`
	CancelRequested      int64          `json:"cancel_requested"`
	MetadataJson         []byte         `json:"metadata_json"`
	OutputExpirySeconds  int64          `json:"output_expiry_seconds"`
	OutputFileID         sql.NullString `json:"output_file_id"`
	ErrorFileID          sql.NullString `json:"error_file_id"`
	RequestTotal         int64          `json:"request_total"`
	RequestCompleted     int64          `json:"request_completed"`
	RequestFailed        int64          `json:"request_failed"`
	UsageKnown           int64          `json:"usage_known"`
	UsageInputTokens     int64          `json:"usage_input_tokens"`
	UsageOutputTokens    int64          `json:"usage_output_tokens"`
	UsageCachedTokens    int64          `json:"usage_cached_tokens"`
	UsageReasoningTokens int64          `json:"usage_reasoning_tokens"`
	CreatedAt            int64          `json:"created_at"`
	InProgressAt         int64          `json:"in_progress_at"`
	ExpiresAt            int64          `json:"expires_at"`
	CancellingAt         sql.NullInt64  `json:"cancelling_at"`
	TerminalAt           sql.NullInt64  `json:"terminal_at"`
	RetentionExpiresAt   int64          `json:"retention_expires_at"`
}

type OpenaiBatchItem struct {
	BatchID             string         `json:"batch_id"`
	Ordinal             int64          `json:"ordinal"`
	CustomID            string         `json:"custom_id"`
	ResultID            string         `json:"result_id"`
	RequestBytes        int64          `json:"request_bytes"`
	RequestCiphertext   []byte         `json:"request_ciphertext"`
	RequestNonce        []byte         `json:"request_nonce"`
	State               string         `json:"state"`
	ResultBytes         sql.NullInt64  `json:"result_bytes"`
	ResultCiphertext    []byte         `json:"result_ciphertext"`
	ResultNonce         []byte         `json:"result_nonce"`
	RequestID           sql.NullString `json:"request_id"`
	AttemptID           sql.NullString `json:"attempt_id"`
	UsageKnown          int64          `json:"usage_known"`
	ReservedResultBytes int64          `json:"reserved_result_bytes"`
	LeaseEpoch          string         `json:"lease_epoch"`
	ClaimedAt           sql.NullInt64  `json:"claimed_at"`
	DispatchStartedAt   sql.NullInt64  `json:"dispatch_started_at"`
	FinishedAt          sql.NullInt64  `json:"finished_at"`
}

type OpenaiFile struct {
	ID            string         `json:"id"`
	OwnerUserID   string         `json:"owner_user_id"`
	KeyID         string         `json:"key_id"`
	Filename      string         `json:"filename"`
	Purpose       string         `json:"purpose"`
	Bytes         int64          `json:"bytes"`
	Ciphertext    []byte         `json:"ciphertext"`
	Nonce         []byte         `json:"nonce"`
	CreatedAt     int64          `json:"created_at"`
	ExpiresAt     int64          `json:"expires_at"`
	ClientPurpose sql.NullString `json:"client_purpose"`
}

type OpenaiUpload struct {
	ID                string         `json:"id"`
	OwnerUserID       string         `json:"owner_user_id"`
	KeyID             string         `json:"key_id"`
	Filename          string         `json:"filename"`
	Purpose           string         `json:"purpose"`
	MimeType          string         `json:"mime_type"`
	ExpectedBytes     int64          `json:"expected_bytes"`
	FileExpirySeconds int64          `json:"file_expiry_seconds"`
	Status            string         `json:"status"`
	FileID            sql.NullString `json:"file_id"`
	CreatedAt         int64          `json:"created_at"`
	ExpiresAt         int64          `json:"expires_at"`
	CompletedAt       sql.NullInt64  `json:"completed_at"`
	CancelledAt       sql.NullInt64  `json:"cancelled_at"`
}

type OpenaiUploadPart struct {
	ID         string `json:"id"`
	UploadID   string `json:"upload_id"`
	Bytes      int64  `json:"bytes"`
	Ciphertext []byte `json:"ciphertext"`
	Nonce      []byte `json:"nonce"`
	CreatedAt  int64  `json:"created_at"`
}

type OpenaiVectorStore struct {
	ID               string        `json:"id"`
	OwnerUserID      string        `json:"owner_user_id"`
	KeyID            string        `json:"key_id"`
	Name             string        `json:"name"`
	Description      string        `json:"description"`
	MetadataJson     []byte        `json:"metadata_json"`
	CreatedAt        int64         `json:"created_at"`
	LastActiveAt     int64         `json:"last_active_at"`
	ExpiresAfterDays sql.NullInt64 `json:"expires_after_days"`
	ExpiresAt        sql.NullInt64 `json:"expires_at"`
}

type OpenaiVectorStoreFile struct {
	VectorStoreID        string         `json:"vector_store_id"`
	FileID               string         `json:"file_id"`
	AttributesJson       []byte         `json:"attributes_json"`
	ChunkingStrategyJson []byte         `json:"chunking_strategy_json"`
	CreatedAt            int64          `json:"created_at"`
	FileBatchID          sql.NullString `json:"file_batch_id"`
}

type OpenaiVectorStoreFileBatch struct {
	ID            string `json:"id"`
	VectorStoreID string `json:"vector_store_id"`
	CreatedAt     int64  `json:"created_at"`
	FileCount     int64  `json:"file_count"`
}

type OperationSetting struct {
	Singleton            int64  `json:"singleton"`
	BackupEnabled        int64  `json:"backup_enabled"`
	BackupIntervalHours  int64  `json:"backup_interval_hours"`
	BackupRetentionCount int64  `json:"backup_retention_count"`
	BackupDestination    string `json:"backup_destination"`
	LocalDirectory       string `json:"local_directory"`
	S3Endpoint           string `json:"s3_endpoint"`
	S3Region             string `json:"s3_region"`
	S3Bucket             string `json:"s3_bucket"`
	S3Prefix             string `json:"s3_prefix"`
	S3AccessKeyEnv       string `json:"s3_access_key_env"`
	S3SecretKeyEnv       string `json:"s3_secret_key_env"`
	RequestRetentionDays int64  `json:"request_retention_days"`
	AuditRetentionDays   int64  `json:"audit_retention_days"`
	Revision             int64  `json:"revision"`
	UpdatedAt            int64  `json:"updated_at"`
}

type PriceVersion struct {
	ID                       string         `json:"id"`
	ConnectionID             string         `json:"connection_id"`
	ModelID                  string         `json:"model_id"`
	InputNanosPerMillion     int64          `json:"input_nanos_per_million"`
	OutputNanosPerMillion    int64          `json:"output_nanos_per_million"`
	Source                   string         `json:"source"`
	EffectiveFrom            int64          `json:"effective_from"`
	EffectiveTo              sql.NullInt64  `json:"effective_to"`
	CreatedBy                sql.NullString `json:"created_by"`
	CreatedAt                int64          `json:"created_at"`
	CacheReadNanosPerMillion sql.NullInt64  `json:"cache_read_nanos_per_million"`
	WeeklyStartMinuteUtc     sql.NullInt64  `json:"weekly_start_minute_utc"`
	WeeklyEndMinuteUtc       sql.NullInt64  `json:"weekly_end_minute_utc"`
	WebSearchNanosPerCall    sql.NullInt64  `json:"web_search_nanos_per_call"`
}

type PricingJob struct {
	ID               string         `json:"id"`
	IdempotencyKey   string         `json:"idempotency_key"`
	ActorUserID      sql.NullString `json:"actor_user_id"`
	ModelID          string         `json:"model_id"`
	ConnectionID     string         `json:"connection_id"`
	FromTime         int64          `json:"from_time"`
	ToTime           int64          `json:"to_time"`
	State            string         `json:"state"`
	AffectedAttempts int64          `json:"affected_attempts"`
	MissingPrices    int64          `json:"missing_prices"`
	DeltaNanos       int64          `json:"delta_nanos"`
	CreatedAt        int64          `json:"created_at"`
	CompletedAt      sql.NullInt64  `json:"completed_at"`
}

type ProviderAdapterScript struct {
	ConnectionID   string `json:"connection_id"`
	RequestScript  string `json:"request_script"`
	ResponseScript string `json:"response_script"`
	UpdatedAt      int64  `json:"updated_at"`
}

type ProviderConnection struct {
	ID                  string `json:"id"`
	Name                string `json:"name"`
	Adapter             string `json:"adapter"`
	BaseUrl             string `json:"base_url"`
	Enabled             int64  `json:"enabled"`
	AllowPrivateNetwork int64  `json:"allow_private_network"`
	TimeoutMs           int64  `json:"timeout_ms"`
	Revision            int64  `json:"revision"`
	CreatedAt           int64  `json:"created_at"`
	UpdatedAt           int64  `json:"updated_at"`
	Preset              string `json:"preset"`
}

type ProviderCredential struct {
	ConnectionID string         `json:"connection_id"`
	Ciphertext   []byte         `json:"ciphertext"`
	Nonce        []byte         `json:"nonce"`
	ExternalRef  sql.NullString `json:"external_ref"`
	UpdatedAt    int64          `json:"updated_at"`
}

type PublicModel struct {
	ID                 string `json:"id"`
	Label              string `json:"label"`
	Description        string `json:"description"`
	TargetConnectionID string `json:"target_connection_id"`
	TargetModelID      string `json:"target_model_id"`
	CapabilitiesJson   string `json:"capabilities_json"`
	Active             int64  `json:"active"`
	Revision           int64  `json:"revision"`
	CreatedAt          int64  `json:"created_at"`
	UpdatedAt          int64  `json:"updated_at"`
	RoutingStrategy    string `json:"routing_strategy"`
	FreeOnly           int64  `json:"free_only"`
}

type PublicModelTarget struct {
	PublicModelID   string `json:"public_model_id"`
	UpstreamModelID string `json:"upstream_model_id"`
	Priority        int64  `json:"priority"`
	Weight          int64  `json:"weight"`
	Enabled         int64  `json:"enabled"`
	CreatedAt       int64  `json:"created_at"`
	UpdatedAt       int64  `json:"updated_at"`
}

type QuotaPeriod struct {
	PolicyID        string        `json:"policy_id"`
	PeriodStart     int64         `json:"period_start"`
	PeriodEnd       sql.NullInt64 `json:"period_end"`
	ConsumedUnits   int64         `json:"consumed_units"`
	ReservedUnits   int64         `json:"reserved_units"`
	LastEffectiveAt int64         `json:"last_effective_at"`
}

type Request struct {
	ID          string        `json:"id"`
	OwnerUserID string        `json:"owner_user_id"`
	KeyID       string        `json:"key_id"`
	Operation   string        `json:"operation"`
	Dialect     string        `json:"dialect"`
	ModelID     string        `json:"model_id"`
	State       string        `json:"state"`
	StartedAt   int64         `json:"started_at"`
	FinishedAt  sql.NullInt64 `json:"finished_at"`
	RetainedAt  sql.NullInt64 `json:"retained_at"`
}

type Reservation struct {
	ID            string        `json:"id"`
	AttemptID     string        `json:"attempt_id"`
	PolicyID      string        `json:"policy_id"`
	PeriodStart   sql.NullInt64 `json:"period_start"`
	ReservedUnits int64         `json:"reserved_units"`
	State         string        `json:"state"`
	CreatedAt     int64         `json:"created_at"`
	SettledAt     sql.NullInt64 `json:"settled_at"`
}

type RouteObservation struct {
	UpstreamModelID     string        `json:"upstream_model_id"`
	Operation           string        `json:"operation"`
	Streaming           int64         `json:"streaming"`
	SuccessCount        int64         `json:"success_count"`
	FailureCount        int64         `json:"failure_count"`
	ConsecutiveFailures int64         `json:"consecutive_failures"`
	EwmaFirstByteMs     sql.NullInt64 `json:"ewma_first_byte_ms"`
	EwmaTotalMs         sql.NullInt64 `json:"ewma_total_ms"`
	CircuitOpenUntil    sql.NullInt64 `json:"circuit_open_until"`
	UpdatedAt           int64         `json:"updated_at"`
}

type SetupToken struct {
	Singleton     int64          `json:"singleton"`
	Verifier      []byte         `json:"verifier"`
	ExpiresAt     int64          `json:"expires_at"`
	ClaimedUserID sql.NullString `json:"claimed_user_id"`
}

type StoredChatCompletion struct {
	ID           string `json:"id"`
	OwnerUserID  string `json:"owner_user_id"`
	KeyID        string `json:"key_id"`
	ModelID      string `json:"model_id"`
	BodyJson     []byte `json:"body_json"`
	RequestJson  []byte `json:"request_json"`
	MetadataJson []byte `json:"metadata_json"`
	CreatedAt    int64  `json:"created_at"`
	ExpiresAt    int64  `json:"expires_at"`
}

type StoredChatCompletionMetadatum struct {
	CompletionID  string `json:"completion_id"`
	MetadataKey   string `json:"metadata_key"`
	MetadataValue string `json:"metadata_value"`
}

type StoredResponse struct {
	ID                    string         `json:"id"`
	OwnerUserID           string         `json:"owner_user_id"`
	KeyID                 string         `json:"key_id"`
	ModelID               string         `json:"model_id"`
	BodyJson              []byte         `json:"body_json"`
	CreatedAt             int64          `json:"created_at"`
	ExpiresAt             int64          `json:"expires_at"`
	State                 string         `json:"state"`
	RequestJson           []byte         `json:"request_json"`
	CancelRequested       int64          `json:"cancel_requested"`
	LeaseEpoch            string         `json:"lease_epoch"`
	ClaimedAt             sql.NullInt64  `json:"claimed_at"`
	FinishedAt            sql.NullInt64  `json:"finished_at"`
	ConversationID        sql.NullString `json:"conversation_id"`
	ConversationRevision  sql.NullInt64  `json:"conversation_revision"`
	ConversationItemsJson []byte         `json:"conversation_items_json"`
	RequestID             sql.NullString `json:"request_id"`
}

type UpstreamModel struct {
	ID               string `json:"id"`
	ConnectionID     string `json:"connection_id"`
	UpstreamID       string `json:"upstream_id"`
	CapabilitiesJson string `json:"capabilities_json"`
	Active           int64  `json:"active"`
	CreatedAt        int64  `json:"created_at"`
	UpdatedAt        int64  `json:"updated_at"`
}

type UsageLedger struct {
	ID             string         `json:"id"`
	AttemptID      string         `json:"attempt_id"`
	EntryType      string         `json:"entry_type"`
	TokenUnits     sql.NullInt64  `json:"token_units"`
	CostNanos      sql.NullInt64  `json:"cost_nanos"`
	IdempotencyKey string         `json:"idempotency_key"`
	ActorUserID    sql.NullString `json:"actor_user_id"`
	Reason         string         `json:"reason"`
	CreatedAt      int64          `json:"created_at"`
}

type User struct {
	ID                    string `json:"id"`
	Email                 string `json:"email"`
	DisplayName           string `json:"display_name"`
	PasswordHash          string `json:"password_hash"`
	Role                  string `json:"role"`
	Status                string `json:"status"`
	CreatedAt             int64  `json:"created_at"`
	UpdatedAt             int64  `json:"updated_at"`
	AuthRevision          int64  `json:"auth_revision"`
	Revision              int64  `json:"revision"`
	InferenceUnrestricted int64  `json:"inference_unrestricted"`
	ScopesJson            string `json:"scopes_json"`
	ModelPatternsJson     string `json:"model_patterns_json"`
	ConnectionIdsJson     string `json:"connection_ids_json"`
}

type UserSession struct {
	ID              string `json:"id"`
	Verifier        []byte `json:"verifier"`
	UserID          string `json:"user_id"`
	ExpiresAt       int64  `json:"expires_at"`
	CreatedAt       int64  `json:"created_at"`
	LastSeenAt      int64  `json:"last_seen_at"`
	AuthenticatedAt int64  `json:"authenticated_at"`
	AuthRevision    int64  `json:"auth_revision"`
	UserAgent       string `json:"user_agent"`
}
