// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package systemdb

import (
	"database/sql"
)

type ActivationToken struct {
	Verifier  []byte `json:"verifier"`
	UserID    string `json:"user_id"`
	Purpose   string `json:"purpose"`
	ExpiresAt int64  `json:"expires_at"`
	CreatedAt int64  `json:"created_at"`
}

type AdmissionClock struct {
	Singleton       int64  `json:"singleton"`
	LastEffectiveAt int64  `json:"last_effective_at"`
	ProcessEpoch    string `json:"process_epoch"`
}

type ApiKey struct {
	ID                string        `json:"id"`
	OwnerUserID       string        `json:"owner_user_id"`
	Label             string        `json:"label"`
	State             string        `json:"state"`
	ScopesJson        string        `json:"scopes_json"`
	ModelPatternsJson string        `json:"model_patterns_json"`
	ConnectionIdsJson string        `json:"connection_ids_json"`
	ExpiresAt         sql.NullInt64 `json:"expires_at"`
	Revision          int64         `json:"revision"`
	CreatedAt         int64         `json:"created_at"`
	UpdatedAt         int64         `json:"updated_at"`
}

type ApiKeySecret struct {
	Selector  string        `json:"selector"`
	Verifier  []byte        `json:"verifier"`
	KeyID     string        `json:"key_id"`
	CreatedAt int64         `json:"created_at"`
	ExpiresAt sql.NullInt64 `json:"expires_at"`
	RevokedAt sql.NullInt64 `json:"revoked_at"`
}

type Attempt struct {
	ID                     string         `json:"id"`
	RequestID              string         `json:"request_id"`
	Ordinal                int64          `json:"ordinal"`
	ConnectionID           string         `json:"connection_id"`
	ModelID                string         `json:"model_id"`
	PriceVersionID         sql.NullString `json:"price_version_id"`
	State                  string         `json:"state"`
	UsageStatus            string         `json:"usage_status"`
	EstimatedTokens        int64          `json:"estimated_tokens"`
	InputTokens            sql.NullInt64  `json:"input_tokens"`
	OutputTokens           sql.NullInt64  `json:"output_tokens"`
	EstimatedCostNanos     sql.NullInt64  `json:"estimated_cost_nanos"`
	AsRecordedCostNanos    sql.NullInt64  `json:"as_recorded_cost_nanos"`
	RestatedCostNanos      sql.NullInt64  `json:"restated_cost_nanos"`
	StartedAt              int64          `json:"started_at"`
	FinishedAt             sql.NullInt64  `json:"finished_at"`
	UpstreamModelRecordID  string         `json:"upstream_model_record_id"`
	UpstreamModelID        string         `json:"upstream_model_id"`
	ConnectionRevision     int64          `json:"connection_revision"`
	TargetDialect          string         `json:"target_dialect"`
	TargetOperation        string         `json:"target_operation"`
	TranslationApplied     int64          `json:"translation_applied"`
	RequestToolCount       int64          `json:"request_tool_count"`
	ResponseToolCallCount  int64          `json:"response_tool_call_count"`
	ToolCallStatus         string         `json:"tool_call_status"`
	SelectionReason        string         `json:"selection_reason"`
	RejectedCandidatesJson string         `json:"rejected_candidates_json"`
}

type AuditEvent struct {
	ID           string         `json:"id"`
	ActorUserID  sql.NullString `json:"actor_user_id"`
	Action       string         `json:"action"`
	ResourceType string         `json:"resource_type"`
	ResourceID   string         `json:"resource_id"`
	DetailJson   string         `json:"detail_json"`
	CreatedAt    int64          `json:"created_at"`
}

type BackupJob struct {
	ID                 string        `json:"id"`
	State              string        `json:"state"`
	Destination        string        `json:"destination"`
	ArchiveName        string        `json:"archive_name"`
	Checksum           string        `json:"checksum"`
	SizeBytes          int64         `json:"size_bytes"`
	SnapshotGeneration string        `json:"snapshot_generation"`
	Error              string        `json:"error"`
	StartedAt          int64         `json:"started_at"`
	FinishedAt         sql.NullInt64 `json:"finished_at"`
}

type BucketState struct {
	PolicyID        string `json:"policy_id"`
	RemainingUnits  int64  `json:"remaining_units"`
	RefillRemainder int64  `json:"refill_remainder"`
	LastRefillAt    int64  `json:"last_refill_at"`
	LastEffectiveAt int64  `json:"last_effective_at"`
}

type CatalogCandidate struct {
	Provider              string        `json:"provider"`
	ModelID               string        `json:"model_id"`
	Label                 string        `json:"label"`
	CapabilitiesJson      string        `json:"capabilities_json"`
	InputNanosPerMillion  sql.NullInt64 `json:"input_nanos_per_million"`
	OutputNanosPerMillion sql.NullInt64 `json:"output_nanos_per_million"`
	Free                  int64         `json:"free"`
	Source                string        `json:"source"`
	SourceVersion         string        `json:"source_version"`
	DiscoveredAt          int64         `json:"discovered_at"`
}

type CatalogRefreshState struct {
	Singleton            int64         `json:"singleton"`
	SourceUrl            string        `json:"source_url"`
	SourceVersion        string        `json:"source_version"`
	LastCheckedAt        sql.NullInt64 `json:"last_checked_at"`
	LastError            string        `json:"last_error"`
	RefreshEnabled       int64         `json:"refresh_enabled"`
	RefreshIntervalHours int64         `json:"refresh_interval_hours"`
}

type ConcurrencyLease struct {
	PolicyID     string         `json:"policy_id"`
	LeaseKind    string         `json:"lease_kind"`
	LeaseID      string         `json:"lease_id"`
	RequestID    string         `json:"request_id"`
	AttemptID    sql.NullString `json:"attempt_id"`
	ProcessEpoch string         `json:"process_epoch"`
	CreatedAt    int64          `json:"created_at"`
}

type Conversation struct {
	ID           string        `json:"id"`
	OwnerUserID  string        `json:"owner_user_id"`
	KeyID        string        `json:"key_id"`
	MetadataJson string        `json:"metadata_json"`
	CreatedAt    int64         `json:"created_at"`
	DeletedAt    sql.NullInt64 `json:"deleted_at"`
	Revision     int64         `json:"revision"`
}

type ConversationItem struct {
	ConversationID string `json:"conversation_id"`
	ID             string `json:"id"`
	Ordinal        int64  `json:"ordinal"`
	BodyJson       []byte `json:"body_json"`
	CreatedAt      int64  `json:"created_at"`
}

type CostAssessment struct {
	ID                 string `json:"id"`
	AttemptID          string `json:"attempt_id"`
	PriceVersionID     string `json:"price_version_id"`
	CalculationVersion int64  `json:"calculation_version"`
	Kind               string `json:"kind"`
	AmountNanos        int64  `json:"amount_nanos"`
	DeltaNanos         int64  `json:"delta_nanos"`
	CreatedAt          int64  `json:"created_at"`
}

type EventOutbox struct {
	Sequence    int64          `json:"sequence"`
	ID          string         `json:"id"`
	EventType   string         `json:"event_type"`
	RequestID   sql.NullString `json:"request_id"`
	AttemptID   sql.NullString `json:"attempt_id"`
	PayloadJson string         `json:"payload_json"`
	CreatedAt   int64          `json:"created_at"`
	DeliveredAt sql.NullInt64  `json:"delivered_at"`
}

type GatewayMetadatum struct {
	Key       string `json:"key"`
	Value     string `json:"value"`
	UpdatedAt string `json:"updated_at"`
}

type LimitPolicy struct {
	ID               string `json:"id"`
	ScopeKind        string `json:"scope_kind"`
	ScopeID          string `json:"scope_id"`
	Metric           string `json:"metric"`
	Algorithm        string `json:"algorithm"`
	Period           string `json:"period"`
	WindowSeconds    int64  `json:"window_seconds"`
	LimitUnits       int64  `json:"limit_units"`
	RefillUnits      int64  `json:"refill_units"`
	RefillIntervalMs int64  `json:"refill_interval_ms"`
	Enabled          int64  `json:"enabled"`
	Revision         int64  `json:"revision"`
	CreatedAt        int64  `json:"created_at"`
	UpdatedAt        int64  `json:"updated_at"`
}

type LoginThrottle struct {
	Subject         []byte `json:"subject"`
	WindowStartedAt int64  `json:"window_started_at"`
	Failures        int64  `json:"failures"`
	BlockedUntil    int64  `json:"blocked_until"`
}

type OperationSetting struct {
	Singleton            int64  `json:"singleton"`
	BackupEnabled        int64  `json:"backup_enabled"`
	BackupIntervalHours  int64  `json:"backup_interval_hours"`
	BackupRetentionCount int64  `json:"backup_retention_count"`
	BackupDestination    string `json:"backup_destination"`
	LocalDirectory       string `json:"local_directory"`
	S3Endpoint           string `json:"s3_endpoint"`
	S3Region             string `json:"s3_region"`
	S3Bucket             string `json:"s3_bucket"`
	S3Prefix             string `json:"s3_prefix"`
	S3AccessKeyEnv       string `json:"s3_access_key_env"`
	S3SecretKeyEnv       string `json:"s3_secret_key_env"`
	RequestRetentionDays int64  `json:"request_retention_days"`
	AuditRetentionDays   int64  `json:"audit_retention_days"`
	Revision             int64  `json:"revision"`
	UpdatedAt            int64  `json:"updated_at"`
}

type PriceVersion struct {
	ID                    string         `json:"id"`
	ConnectionID          string         `json:"connection_id"`
	ModelID               string         `json:"model_id"`
	InputNanosPerMillion  int64          `json:"input_nanos_per_million"`
	OutputNanosPerMillion int64          `json:"output_nanos_per_million"`
	Source                string         `json:"source"`
	EffectiveFrom         int64          `json:"effective_from"`
	EffectiveTo           sql.NullInt64  `json:"effective_to"`
	CreatedBy             sql.NullString `json:"created_by"`
	CreatedAt             int64          `json:"created_at"`
}

type PricingJob struct {
	ID               string         `json:"id"`
	IdempotencyKey   string         `json:"idempotency_key"`
	ActorUserID      sql.NullString `json:"actor_user_id"`
	ModelID          string         `json:"model_id"`
	ConnectionID     string         `json:"connection_id"`
	FromTime         int64          `json:"from_time"`
	ToTime           int64          `json:"to_time"`
	State            string         `json:"state"`
	AffectedAttempts int64          `json:"affected_attempts"`
	MissingPrices    int64          `json:"missing_prices"`
	DeltaNanos       int64          `json:"delta_nanos"`
	CreatedAt        int64          `json:"created_at"`
	CompletedAt      sql.NullInt64  `json:"completed_at"`
}

type ProviderConnection struct {
	ID                  string `json:"id"`
	Name                string `json:"name"`
	Adapter             string `json:"adapter"`
	BaseUrl             string `json:"base_url"`
	Enabled             int64  `json:"enabled"`
	AllowPrivateNetwork int64  `json:"allow_private_network"`
	TimeoutMs           int64  `json:"timeout_ms"`
	Revision            int64  `json:"revision"`
	CreatedAt           int64  `json:"created_at"`
	UpdatedAt           int64  `json:"updated_at"`
	Preset              string `json:"preset"`
}

type ProviderCredential struct {
	ConnectionID string         `json:"connection_id"`
	Ciphertext   []byte         `json:"ciphertext"`
	Nonce        []byte         `json:"nonce"`
	ExternalRef  sql.NullString `json:"external_ref"`
	UpdatedAt    int64          `json:"updated_at"`
}

type PublicModel struct {
	ID                 string `json:"id"`
	Label              string `json:"label"`
	Description        string `json:"description"`
	TargetConnectionID string `json:"target_connection_id"`
	TargetModelID      string `json:"target_model_id"`
	CapabilitiesJson   string `json:"capabilities_json"`
	Active             int64  `json:"active"`
	Revision           int64  `json:"revision"`
	CreatedAt          int64  `json:"created_at"`
	UpdatedAt          int64  `json:"updated_at"`
	RoutingStrategy    string `json:"routing_strategy"`
	FreeOnly           int64  `json:"free_only"`
}

type PublicModelTarget struct {
	PublicModelID   string `json:"public_model_id"`
	UpstreamModelID string `json:"upstream_model_id"`
	Priority        int64  `json:"priority"`
	Weight          int64  `json:"weight"`
	Enabled         int64  `json:"enabled"`
	CreatedAt       int64  `json:"created_at"`
	UpdatedAt       int64  `json:"updated_at"`
}

type QuotaPeriod struct {
	PolicyID        string        `json:"policy_id"`
	PeriodStart     int64         `json:"period_start"`
	PeriodEnd       sql.NullInt64 `json:"period_end"`
	ConsumedUnits   int64         `json:"consumed_units"`
	ReservedUnits   int64         `json:"reserved_units"`
	LastEffectiveAt int64         `json:"last_effective_at"`
}

type Request struct {
	ID          string        `json:"id"`
	OwnerUserID string        `json:"owner_user_id"`
	KeyID       string        `json:"key_id"`
	Operation   string        `json:"operation"`
	Dialect     string        `json:"dialect"`
	ModelID     string        `json:"model_id"`
	State       string        `json:"state"`
	StartedAt   int64         `json:"started_at"`
	FinishedAt  sql.NullInt64 `json:"finished_at"`
	RetainedAt  sql.NullInt64 `json:"retained_at"`
}

type Reservation struct {
	ID            string        `json:"id"`
	AttemptID     string        `json:"attempt_id"`
	PolicyID      string        `json:"policy_id"`
	PeriodStart   sql.NullInt64 `json:"period_start"`
	ReservedUnits int64         `json:"reserved_units"`
	State         string        `json:"state"`
	CreatedAt     int64         `json:"created_at"`
	SettledAt     sql.NullInt64 `json:"settled_at"`
}

type RouteObservation struct {
	UpstreamModelID     string        `json:"upstream_model_id"`
	Operation           string        `json:"operation"`
	Streaming           int64         `json:"streaming"`
	SuccessCount        int64         `json:"success_count"`
	FailureCount        int64         `json:"failure_count"`
	ConsecutiveFailures int64         `json:"consecutive_failures"`
	EwmaFirstByteMs     sql.NullInt64 `json:"ewma_first_byte_ms"`
	EwmaTotalMs         sql.NullInt64 `json:"ewma_total_ms"`
	CircuitOpenUntil    sql.NullInt64 `json:"circuit_open_until"`
	UpdatedAt           int64         `json:"updated_at"`
}

type SetupToken struct {
	Singleton     int64          `json:"singleton"`
	Verifier      []byte         `json:"verifier"`
	ExpiresAt     int64          `json:"expires_at"`
	ClaimedUserID sql.NullString `json:"claimed_user_id"`
}

type StoredResponse struct {
	ID                    string         `json:"id"`
	OwnerUserID           string         `json:"owner_user_id"`
	KeyID                 string         `json:"key_id"`
	ModelID               string         `json:"model_id"`
	BodyJson              []byte         `json:"body_json"`
	CreatedAt             int64          `json:"created_at"`
	ExpiresAt             int64          `json:"expires_at"`
	State                 string         `json:"state"`
	RequestJson           []byte         `json:"request_json"`
	CancelRequested       int64          `json:"cancel_requested"`
	LeaseEpoch            string         `json:"lease_epoch"`
	ClaimedAt             sql.NullInt64  `json:"claimed_at"`
	FinishedAt            sql.NullInt64  `json:"finished_at"`
	ConversationID        sql.NullString `json:"conversation_id"`
	ConversationRevision  sql.NullInt64  `json:"conversation_revision"`
	ConversationItemsJson []byte         `json:"conversation_items_json"`
}

type UpstreamModel struct {
	ID               string `json:"id"`
	ConnectionID     string `json:"connection_id"`
	UpstreamID       string `json:"upstream_id"`
	CapabilitiesJson string `json:"capabilities_json"`
	Active           int64  `json:"active"`
	CreatedAt        int64  `json:"created_at"`
	UpdatedAt        int64  `json:"updated_at"`
}

type UsageLedger struct {
	ID             string         `json:"id"`
	AttemptID      string         `json:"attempt_id"`
	EntryType      string         `json:"entry_type"`
	TokenUnits     sql.NullInt64  `json:"token_units"`
	CostNanos      sql.NullInt64  `json:"cost_nanos"`
	IdempotencyKey string         `json:"idempotency_key"`
	ActorUserID    sql.NullString `json:"actor_user_id"`
	Reason         string         `json:"reason"`
	CreatedAt      int64          `json:"created_at"`
}

type User struct {
	ID                    string `json:"id"`
	Email                 string `json:"email"`
	DisplayName           string `json:"display_name"`
	PasswordHash          string `json:"password_hash"`
	Role                  string `json:"role"`
	Status                string `json:"status"`
	CreatedAt             int64  `json:"created_at"`
	UpdatedAt             int64  `json:"updated_at"`
	AuthRevision          int64  `json:"auth_revision"`
	Revision              int64  `json:"revision"`
	InferenceUnrestricted int64  `json:"inference_unrestricted"`
	ScopesJson            string `json:"scopes_json"`
	ModelPatternsJson     string `json:"model_patterns_json"`
	ConnectionIdsJson     string `json:"connection_ids_json"`
}

type UserSession struct {
	ID              string `json:"id"`
	Verifier        []byte `json:"verifier"`
	UserID          string `json:"user_id"`
	ExpiresAt       int64  `json:"expires_at"`
	CreatedAt       int64  `json:"created_at"`
	LastSeenAt      int64  `json:"last_seen_at"`
	AuthenticatedAt int64  `json:"authenticated_at"`
	AuthRevision    int64  `json:"auth_revision"`
	UserAgent       string `json:"user_agent"`
}
