// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: system.sql

package systemdb

import (
	"context"
)

const getGatewayMetadata = `-- name: GetGatewayMetadata :one
SELECT value FROM gateway_metadata WHERE key = ? LIMIT 1
`

func (q *Queries) GetGatewayMetadata(ctx context.Context, key string) (string, error) {
	row := q.db.QueryRowContext(ctx, getGatewayMetadata, key)
	var value string
	err := row.Scan(&value)
	return value, err
}

const setGatewayMetadata = `-- name: SetGatewayMetadata :exec
INSERT INTO gateway_metadata (key, value, updated_at)
VALUES (?, ?, CURRENT_TIMESTAMP)
ON CONFLICT (key) DO UPDATE SET value = excluded.value, updated_at = CURRENT_TIMESTAMP
`

type SetGatewayMetadataParams struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

func (q *Queries) SetGatewayMetadata(ctx context.Context, arg SetGatewayMetadataParams) error {
	_, err := q.db.ExecContext(ctx, setGatewayMetadata, arg.Key, arg.Value)
	return err
}
