"use client";

import Link from "next/link";
import { useEffect, useState, type FormEvent } from "react";
import { AppShell } from "@/components/app-shell";
import { useGatewayUser } from "@/components/setup-gate";
import { Button, buttonVariants } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { GatewayAPIError, gatewayAPI, type ProviderConnection } from "@/lib/api-client";

const capabilities=["chat","embeddings","count_tokens"];

export default function ProvidersPage(){
 const user=useGatewayUser();const [items,setItems]=useState<ProviderConnection[]>([]);const [error,setError]=useState("");const [busy,setBusy]=useState(false);
 async function load(){try{setItems((await gatewayAPI.connections()).data);setError("")}catch(failure){setError(failure instanceof GatewayAPIError?failure.message:"Providers are unavailable")}}
 useEffect(()=>{void load()},[]);
 async function create(event:FormEvent<HTMLFormElement>){event.preventDefault();const element=event.currentTarget;const form=new FormData(element);setBusy(true);try{await gatewayAPI.createConnection({name:String(form.get("name")),adapter:String(form.get("adapter")) as ProviderConnection["adapter"],base_url:String(form.get("base_url")),enabled:true,allow_private_network:form.get("allow_private_network")==="on",timeout_ms:Number(form.get("timeout_ms"))});element.reset();await load()}catch(failure){setError(failure instanceof GatewayAPIError?failure.message:"Connection could not be created")}finally{setBusy(false)}}
 async function credential(event:FormEvent<HTMLFormElement>,id:string){event.preventDefault();const element=event.currentTarget;const form=new FormData(element);if(!window.confirm("Replace this provider credential? Existing requests keep their recorded provenance."))return;setBusy(true);try{const mode=String(form.get("mode"));await gatewayAPI.putProviderCredential(id,mode==="external"?{external_ref:String(form.get("value"))}:{credential:String(form.get("value"))});element.reset();await load()}catch(failure){setError(failure instanceof GatewayAPIError?failure.message:"Credential could not be saved")}finally{setBusy(false)}}
 async function addModel(event:FormEvent<HTMLFormElement>,id:string){event.preventDefault();const element=event.currentTarget;const form=new FormData(element);setBusy(true);try{await gatewayAPI.createUpstreamModel(id,{upstream_id:String(form.get("upstream_id")),capabilities:form.getAll("capabilities").map(String)});element.reset()}catch(failure){setError(failure instanceof GatewayAPIError?failure.message:"Upstream model could not be added")}finally{setBusy(false)}}
 async function toggle(item:ProviderConnection){if(!window.confirm(`${item.enabled?"Disable":"Enable"} ${item.name}?`))return;setBusy(true);try{await gatewayAPI.updateConnection(item,{name:item.name,adapter:item.adapter,base_url:item.base_url,enabled:!item.enabled,allow_private_network:item.allow_private_network,timeout_ms:item.timeout_ms});await load()}catch(failure){setError(failure instanceof GatewayAPIError?failure.message:"Connection could not be updated")}finally{setBusy(false)}}
 if(user?.role==="member")return <AppShell active="Providers"><main id="main-content" className="content"><h1>Administrator access required.</h1></main></AppShell>;
 return <AppShell active="Providers"><main id="main-content" className="content management-page"><header className="page-header"><div><p className="context">Provider boundary</p><h1>Providers</h1><p className="lede">Connect native APIs. Stored credentials are encrypted and never shown again.</p></div></header>{error&&<p className="form-error" role="alert">{error}</p>}
 <Card className="panel"><h2>Add connection</h2><form onSubmit={create}><div className="inline-fields"><Field id="name" label="Name" required/><div className="field"><Label htmlFor="adapter">Adapter</Label><select id="adapter" name="adapter" className="select"><option value="openai">OpenAI</option><option value="anthropic">Anthropic</option><option value="gemini">Gemini</option><option value="openai_compatible">OpenAI compatible</option></select></div></div><Field id="base_url" label="Versioned base URL" type="url" placeholder="https://api.openai.com/v1" required/><div className="inline-fields"><Field id="timeout_ms" label="Timeout (ms)" type="number" defaultValue="60000" required/><label className="checkbox-row"><input type="checkbox" name="allow_private_network"/> Allow local/private HTTP for this connection</label></div><Button disabled={busy}>Add connection</Button></form></Card>
 <section className="section-block"><h2>{items.length} connections</h2><div className="resource-list">{items.map(item=><Card className="panel" key={item.id}><div className="resource-row-main"><div><strong>{item.name}</strong><small>{item.adapter.replaceAll("_"," ")} · {item.base_url} · credential {item.credential_state} · {item.enabled?"enabled":"disabled"}</small><code>{item.id}</code></div><Button variant="outline" disabled={busy} onClick={()=>toggle(item)}>{item.enabled?"Disable":"Enable"}</Button></div><details className="grant-editor"><summary>Replace credential</summary><form onSubmit={event=>credential(event,item.id)}><div className="inline-fields"><div className="field"><Label htmlFor={`mode-${item.id}`}>Storage</Label><select id={`mode-${item.id}`} className="select" name="mode"><option value="stored">Encrypted local value</option><option value="external">Environment reference</option></select></div><Field id={`credential-${item.id}`} name="value" label="Credential or env:NAME" type="password" required/></div><Button disabled={busy}>Replace credential</Button></form></details><details className="grant-editor"><summary>Add upstream model</summary><form onSubmit={event=>addModel(event,item.id)}><Field id={`upstream-${item.id}`} name="upstream_id" label="Upstream model ID" required/><fieldset className="scope-grid"><legend>Capabilities</legend>{capabilities.map(value=><label key={value}><input type="checkbox" name="capabilities" value={value}/><span>{value.replaceAll("_"," ")}</span></label>)}</fieldset><Button disabled={busy}>Add upstream model</Button></form></details></Card>)}</div></section>{items.length > 0 && <div className="next-step"><div><strong>Next: publish a model</strong><small>Map a stable public model name to one of these upstream models.</small></div><Link className={buttonVariants()} href="/models/">Continue to models</Link></div>}</main></AppShell>
}
function Field({id,name,label,type="text",placeholder,defaultValue,required=false}:{id:string;name?:string;label:string;type?:string;placeholder?:string;defaultValue?:string;required?:boolean}){return <div className="field"><Label htmlFor={id}>{label}</Label><Input id={id} name={name??id} type={type} placeholder={placeholder} defaultValue={defaultValue} required={required}/></div>}

