"use client";

import Link from "next/link";
import { useEffect, useState, type FormEvent } from "react";
import { AppShell } from "@/components/app-shell";
import { useGatewayUser } from "@/components/setup-gate";
import { Button, buttonVariants } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { GatewayAPIError, gatewayAPI, type ProviderConnection, type ProviderPreset } from "@/lib/api-client";

const capabilities=["chat","embeddings","count_tokens"];

export default function ProvidersPage(){
 const user=useGatewayUser();const [items,setItems]=useState<ProviderConnection[]>([]);const [presets,setPresets]=useState<ProviderPreset[]>([]);const [selectedPreset,setSelectedPreset]=useState("");const [adapter,setAdapter]=useState<ProviderConnection["adapter"]>("openai");const [error,setError]=useState("");const [busy,setBusy]=useState(false);const selected=presets.find(preset=>preset.id===selectedPreset);
 async function load(){try{const [connections,availablePresets]=await Promise.all([gatewayAPI.connections(),gatewayAPI.providerPresets()]);setItems(connections.data);setPresets(availablePresets.data);setError("")}catch(failure){setError(failure instanceof GatewayAPIError?failure.message:"Providers are unavailable")}}
 useEffect(()=>{void load()},[]);
 async function create(event:FormEvent<HTMLFormElement>){event.preventDefault();const element=event.currentTarget;const form=new FormData(element);setBusy(true);try{await gatewayAPI.createConnection({name:String(form.get("name")),preset:String(form.get("preset")),adapter:String(form.get("adapter")) as ProviderConnection["adapter"],base_url:String(form.get("base_url")),enabled:true,allow_private_network:form.get("allow_private_network")==="on",timeout_ms:Number(form.get("timeout_ms"))});element.reset();setSelectedPreset("");setAdapter("openai");await load()}catch(failure){setError(failure instanceof GatewayAPIError?failure.message:"Connection could not be created")}finally{setBusy(false)}}
 async function credential(event:FormEvent<HTMLFormElement>,id:string){event.preventDefault();const element=event.currentTarget;const form=new FormData(element);if(!window.confirm("Replace this provider credential? Existing requests keep their recorded provenance."))return;setBusy(true);try{const mode=String(form.get("mode"));await gatewayAPI.putProviderCredential(id,mode==="external"?{external_ref:String(form.get("value"))}:{credential:String(form.get("value"))});element.reset();await load()}catch(failure){setError(failure instanceof GatewayAPIError?failure.message:"Credential could not be saved")}finally{setBusy(false)}}
 async function addModel(event:FormEvent<HTMLFormElement>,id:string){event.preventDefault();const element=event.currentTarget;const form=new FormData(element);setBusy(true);try{await gatewayAPI.createUpstreamModel(id,{upstream_id:String(form.get("upstream_id")),capabilities:form.getAll("capabilities").map(String)});element.reset()}catch(failure){setError(failure instanceof GatewayAPIError?failure.message:"Upstream model could not be added")}finally{setBusy(false)}}
 async function toggle(item:ProviderConnection){if(!window.confirm(`${item.enabled?"Disable":"Enable"} ${item.name}?`))return;setBusy(true);try{await gatewayAPI.updateConnection(item,{name:item.name,preset:item.preset,adapter:item.adapter,base_url:item.base_url,enabled:!item.enabled,allow_private_network:item.allow_private_network,timeout_ms:item.timeout_ms});await load()}catch(failure){setError(failure instanceof GatewayAPIError?failure.message:"Connection could not be updated")}finally{setBusy(false)}}
 if(user?.role==="member")return <AppShell active="Providers"><main id="main-content" className="content"><h1>Administrator access required.</h1></main></AppShell>;
 return <AppShell active="Providers"><main id="main-content" className="content management-page"><header className="page-header"><div><p className="context">Provider boundary</p><h1>Providers</h1><p className="lede">Connect native APIs. Stored credentials are encrypted and never shown again.</p></div></header>{error&&<p className="form-error" role="alert">{error}</p>}
 <Card className="panel"><h2>Add connection</h2><form onSubmit={create}><div className="inline-fields"><Field id="name" label="Name" required/><div className="field"><Label htmlFor="preset">Provider preset</Label><select id="preset" name="preset" className="select" value={selectedPreset||"custom"} onChange={event=>{const value=event.target.value==="custom"?"":event.target.value;setSelectedPreset(value);setAdapter(presets.find(preset=>preset.id===value)?.adapter??"openai")}}><option value="custom">Custom</option>{presets.map(preset=><option key={preset.id} value={preset.id}>{preset.label}</option>)}</select></div></div>{selected&&<p className="help-text">Uses {selected.adapter.replaceAll("_"," ")}{selected.base_url?` at ${selected.base_url}`:" with your resource URL"}. Supported gateway operations: {selected.operations.join(", ")}. <a href={selected.documentation_url} target="_blank" rel="noreferrer">Provider documentation</a> reviewed {selected.reviewed_at}.</p>}<div className="inline-fields"><div className="field"><Label htmlFor="adapter">Adapter</Label>{selected&&<input type="hidden" name="adapter" value={adapter}/>}<select id="adapter" name={selected?undefined:"adapter"} className="select" value={adapter} disabled={Boolean(selected)} onChange={event=>setAdapter(event.target.value as ProviderConnection["adapter"])}><option value="openai">OpenAI</option><option value="anthropic">Anthropic</option><option value="gemini">Gemini</option><option value="openai_compatible">OpenAI compatible</option></select></div>{selected?.base_url?<div className="field"><Label htmlFor="base_url">Base URL</Label><Input id="base_url" name="base_url" type="url" value={selected.base_url} readOnly/></div>:<Field id="base_url" label={selected?.base_url_required?"Resource base URL":"Versioned base URL"} type="url" placeholder={selected?.base_url_required?"https://your-resource.example/openai/v1":"https://api.example.com/v1"} required/>}</div><div className="inline-fields"><Field id="timeout_ms" label="Timeout (ms)" type="number" defaultValue="60000" required/>{selected?<label className="checkbox-row"><input type="checkbox" checked={selected.private_network} disabled readOnly/> {selected.private_network?"Local/private network enabled by preset":"Public HTTPS endpoint"}</label>:<label className="checkbox-row"><input type="checkbox" name="allow_private_network"/> Allow local/private HTTP for this connection</label>}</div><Button disabled={busy}>Add connection</Button></form><p className="help-text">Presets pin the reviewed adapter and endpoint rules. Ollama uses a local endpoint without credentials. Cloud presets require the resource URL shown by the provider.</p></Card>
 <section className="section-block"><h2>{items.length} connections</h2><div className="resource-list">{items.map(item=><Card className="panel" key={item.id}><div className="resource-row-main"><div><strong>{item.name}</strong><small>{item.preset} · {item.adapter.replaceAll("_"," ")} · {item.base_url} · credential {item.credential_state} · {item.enabled?"enabled":"disabled"}</small><code>{item.id}</code></div><Button variant="outline" disabled={busy} onClick={()=>toggle(item)}>{item.enabled?"Disable":"Enable"}</Button></div>{item.preset!=="ollama"&&<details className="grant-editor"><summary>Replace credential</summary><form onSubmit={event=>credential(event,item.id)}><div className="inline-fields"><div className="field"><Label htmlFor={`mode-${item.id}`}>Storage</Label><select id={`mode-${item.id}`} className="select" name="mode"><option value="stored">Encrypted local value</option><option value="external">Environment reference</option></select></div><Field id={`credential-${item.id}`} name="value" label="Credential or env:NAME" type="password" required/></div><Button disabled={busy}>Replace credential</Button></form></details>}<details className="grant-editor"><summary>Add upstream model</summary><form onSubmit={event=>addModel(event,item.id)}><Field id={`upstream-${item.id}`} name="upstream_id" label="Upstream model ID" required/><fieldset className="scope-grid"><legend>Capabilities</legend>{capabilities.map(value=><label key={value}><input type="checkbox" name="capabilities" value={value}/><span>{value.replaceAll("_"," ")}</span></label>)}</fieldset><Button disabled={busy}>Add upstream model</Button></form></details></Card>)}</div></section>{items.length > 0 && <div className="next-step"><div><strong>Next: publish a model</strong><small>Map a stable public model name to one of these upstream models.</small></div><Link className={buttonVariants()} href="/models/">Continue to models</Link></div>}</main></AppShell>
}
function Field({id,name,label,type="text",placeholder,defaultValue,required=false}:{id:string;name?:string;label:string;type?:string;placeholder?:string;defaultValue?:string;required?:boolean}){return <div className="field"><Label htmlFor={id}>{label}</Label><Input id={id} name={name??id} type={type} placeholder={placeholder} defaultValue={defaultValue} required={required}/></div>}
