import type { CapabilityDetail } from "@/features/providers/types/providers.types";

export type RouteStrategy = "fixed" | "ordered_fallback" | "weighted" | "lowest_cost" | "lowest_latency";
export type PublicModel = { id: string; label: string; description: string; target_connection_id: string; target_model_id: string; upstream_id: string; adapter: string; adapter_label: string; capabilities: string[]; capability_details: CapabilityDetail[]; active: boolean; revision: number; routing_strategy: RouteStrategy; free_only: boolean; routing_policy: { allowed_strategies: RouteStrategy[]; max_targets_by_strategy: Partial<Record<RouteStrategy, number>>; free_only_allowed: boolean; free_only_label: string; priority_field: { label: string; min: number; max: number; default: number }; weight_field: { label: string; min: number; max: number; default: number }; strategies: { id: RouteStrategy; label: string }[] } };
export type RouteTargetInput = { upstream_model_id: string; priority: number; weight: number; enabled: boolean };
export type RoutePlan = { model_id: string; strategy: RouteStrategy; free_only: boolean; selection_reason: string; selection_message: string; targets: { upstream_model_id: string; connection_id: string; upstream_id: string; adapter: string; capabilities: string[]; priority: number; weight: number; estimated_cost_usd?: string; latency_ms?: number; sample_count: number; circuit_open_until?: string }[]; rejected: { upstream_model_id: string; connection_id: string; reason: string; message: string }[] };
export type CatalogCandidate = { provider: string; model_id: string; label: string; capabilities: string[]; capability_details: CapabilityDetail[]; input_nanos_per_million?: number; output_nanos_per_million?: number; free: boolean; source: string; source_version: string; discovered_at: string };
export type RoutePreviewInput = { operation: string; streaming: boolean; estimated_input_tokens: number; estimated_output_tokens: number };
export type CatalogState = { source_url: string; source_version: string; last_checked_at: string | null; last_error: string; refresh_enabled: boolean; refresh_interval_hours: number };
export type CatalogPage = { data: CatalogCandidate[]; state: CatalogState; next_cursor: string; has_more: boolean };
export type CatalogModel = Pick<PublicModel, "id" | "label" | "description" | "adapter" | "adapter_label" | "capabilities" | "capability_details">;
