// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: data.sql

package datadb

import (
	"context"
)

const getProjectionMetadata = `-- name: GetProjectionMetadata :one
SELECT value FROM projection_metadata WHERE key = ? LIMIT 1
`

func (q *Queries) GetProjectionMetadata(ctx context.Context, key string) (string, error) {
	row := q.db.QueryRowContext(ctx, getProjectionMetadata, key)
	var value string
	err := row.Scan(&value)
	return value, err
}

const setProjectionMetadata = `-- name: SetProjectionMetadata :exec
INSERT INTO projection_metadata (key, value, updated_at)
VALUES (?, ?, CURRENT_TIMESTAMP)
ON CONFLICT (key) DO UPDATE SET value = excluded.value, updated_at = CURRENT_TIMESTAMP
`

type SetProjectionMetadataParams struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

func (q *Queries) SetProjectionMetadata(ctx context.Context, arg SetProjectionMetadataParams) error {
	_, err := q.db.ExecContext(ctx, setProjectionMetadata, arg.Key, arg.Value)
	return err
}
