// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package datadb

type ProjectionMetadatum struct {
	Key       string `json:"key"`
	Value     string `json:"value"`
	UpdatedAt string `json:"updated_at"`
}
